name: tokencost
description: >-
  Clientside token counting + price estimation for LLM apps and AI agents
  ported to Dart from Python package at https://github.com/AgentOps-AI/tokencost.
version: 0.2.8
repository: https://github.com/matteodg/tokencost

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  fpdart: ^1.1.0
  freezed_annotation: ^2.4.1
  http: ^1.2.1
  json_annotation: ^4.9.0
  money2: ^5.0.1
  tiktoken: ^1.0.3

dev_dependencies:
  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  test: ^1.25.5
  very_good_analysis: ^5.1.0

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
