name: tokencost
description: >-
  Clientside token counting + price estimation for LLM apps and AI agents
  ported to Dart from Python package at https://github.com/AgentOps-AI/tokencost.
version: 0.2.1
repository: https://github.com/matteodg/tokencost

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  fpdart: ^1.1.0
  freezed_annotation: ^2.4.1
  http: ^1.2.1
  json_annotation: ^4.8.1
  money2: ^4.1.0
  tiktoken: ^1.0.3

dev_dependencies:
  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  test: ^1.25.2
  very_good_analysis: ^5.1.0

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
