name: tokencost
description: >-
  Clientside token counting + price estimation for LLM apps and AI agents
  ported to Dart from Python package at https://github.com/AgentOps-AI/tokencost.
version: 0.0.6
repository: https://github.com/matteodg/tokencost

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  tiktoken: ^1.0.3
  yaml: ^3.1.2

dev_dependencies:
  test: ^1.25.2
  very_good_analysis: ^5.1.0

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
